markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Peter Backman
url: http://peteb.github.io
description: A fantastic blog that is fantastic.
github: peteb
gravatar_url: http://gravatar.com/avatar/d9254d4d89316830d776a5eb104d1075
